<a href="https://colab.research.google.com/github/rkmaccha/NLP_Workbook/blob/main/NLP_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TEXT REPRESENTATION

### BAG OF WORDS

In [2]:
# import libraries
import pandas as pd
import numpy as np

In [3]:
# Bag of Words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
# creating a dummy data:
df= pd.DataFrame({'text':['audience watch ram4uni','ram4uni watch ram4uni','audience write comments','ram4uni write comments'],'output':[1,1,0,0] })

In [5]:
df

text  output
0   audience watch ram4uni       1
1    ram4uni watch ram4uni       1
2  audience write comments       0
3   ram4uni write comments       0

In [6]:
bow = cv.fit_transform(df['text'])

In [7]:
bow

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [8]:
cv.vocabulary_

{'audience': 0, 'comments': 1, 'ram4uni': 2, 'watch': 3, 'write': 4}

In [9]:
print(bow[0].toarray())

[[1 0 1 1 0]]


In [10]:
print(bow[2].toarray())

[[1 1 0 0 1]]


In [13]:
cv.transform(['ram4uni watch and write comments on ram4uni'])

<1x5 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [14]:
cv.transform(['ram4uni watch and write comments on ram4uni']).toarray()

array([[0, 1, 2, 1, 1]])